### ISSUE TITLE
--pull-details not working: TypeError

### ISSUE THREAD

**Issue by mibe** [josegonzalez/python-github-backup#115]
I'm getting a TypeError error when backing up my repos, specifically the comments to a pull request. 

Here are the last relevant lines:

```
Saving 23 pull requests to disk
Requesting https://api.github.com/repos/mibe/FeedWriter/pulls/1/comments?page=1&per_page=100
Traceback (most recent call last):
  File "/usr/local/bin/github-backup", line 1035, in <module>
    main()
  File "/usr/local/bin/github-backup", line 1030, in main
    backup_repositories(args, output_directory, repositories)
  File "/usr/local/bin/github-backup", line 691, in backup_repositories
    backup_pulls(args, repo_cwd, repository, repos_template)
  File "/usr/local/bin/github-backup", line 813, in backup_pulls
    pulls[number]['comment_data'] = retrieve_data(args, template)
TypeError: list indices must be integers or slices, not str
```

This was the command line:
`github-backup -t $TOKEN --all --pull-details --gists -o . mibe`

```
$ github-backup --version:
github-backup 0.23.0
$ python3 --version:
Python 3.5.3
```

**Comment by josegonzalez** [comment]
Pull requests welcome.

**Comment by mibe** [comment]
It looks like this bug is specific to the `--pull-details` argument. The error disappears when omitting this parameter.

**Comment by whwright** [comment]
https://github.com/josegonzalez/python-github-backup/pull/118

**Comment by josegonzalez** [comment]
Closing as there is a merged pull request.

**Comment by mibe** [comment]
I can confirm 0.24.0 does not crash when using `--pull-details`.
