### ISSUE TITLE
Include repository security advisories

### ISSUE THREAD

**Issue by lukasbestle** [josegonzalez/python-github-backup#243]
See https://docs.github.com/en/rest/security-advisories/repository-advisories?apiVersion=2022-11-28#list-repository-security-advisories

This would make the backup more complete.

**Comment by josegonzalez** [comment]
This project is considered feature complete for the primary maintainer @josegonzalez. If you would like a bugfix or enhancement, pull requests are welcome. Feel free to contact the maintainer for consulting estimates if you'd like to sponsor the work instead.

**Comment by AuroraDysis** [comment]
I encountered a crash when running the backup tool. It appears to be caused by the recent addition of "security advisories" backup.

```
2026-01-14T00:00:12.841: API Error: 404 Not Found for https://api.github.com/repos/<username>/<repo_name>/security-advisories?per_page=100
Traceback (most recent call last):
  File "/path/to/.venv/bin/github-backup", line 10, in <module>
    sys.exit(main())
            ~~~~^^
  File "/path/to/.venv/lib/python3.13/site-packages/github_backup/cli.py", line 83, in main
    backup_repositories(args, output_directory, repositories)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/.venv/lib/python3.13/site-packages/github_backup/github_backup.py", line 1818, in backup_repositories
    backup_security_advisories(args, repo_cwd, repository, repos_template)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/.venv/lib/python3.13/site-packages/github_backup/github_backup.py", line 2048, in backup_security_advisories
    _advisories = retrieve_data(args, template)
  File "/path/to/.venv/lib/python3.13/site-packages/github_backup/github_backup.py", line 739, in retrieve_data
    return list(fetch_all())
  File "/path/to/.venv/lib/python3.13/site-packages/github_backup/github_backup.py", line 664, in fetch_all
    http_response = make_request_with_retry(request, auth, args.max_retries)
  File "/path/to/.venv/lib/python3.13/site-packages/github_backup/github_backup.py", line 756, in make_request_with_retry
    return urlopen(request, context=https_ctx)
  File "/path/to/.local/share/uv/python/cpython-3.13.5-linux-x86_64-gnu/lib/python3.13/urllib/request.py", line 189, in urlopen
    return opener.open(url, data, timeout)
            ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/path/to/.local/share/uv/python/cpython-3.13.5-linux-x86_64-gnu/lib/python3.13/urllib/request.py", line 495, in open
    response = meth(req, response)
  File "/path/to/.local/share/uv/python/cpython-3.13.5-linux-x86_64-gnu/lib/python3.13/urllib/request.py", line 604, in http_response
    response = self.parent.error(
        'http', request, response, code, msg, hdrs)
  File "/path/to/.local/share/uv/python/cpython-3.13.5-linux-x86_64-gnu/lib/python3.13/urllib/request.py", line 533, in error
    return self._call_chain(*args)
            ~~~~~~~~~~~~~~~~^^^^^^^
  File "/path/to/.local/share/uv/python/cpython-3.13.5-linux-x86_64-gnu/lib/python3.13/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/path/to/.local/share/uv/python/cpython-3.13.5-linux-x86_64-gnu/lib/python3.13/urllib/request.py", line 613, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by AuroraDysis** [comment]
I'm using the `--all` option and the `--token` option for authentication (Personal Access Tokens (classic)). It's my own private repo, and the `security_events` scope has been enabled, so I don't think the problem is on my side.

**Comment by lukasbestle** [comment]
It's weird because we have several private repos and we are not paying for any of them. I'll try to reproduce this.
