### ISSUE TITLE
NameError: global name 'auth' is not defined

### ISSUE THREAD

**Issue by geier** [josegonzalez/python-github-backup#25]
When running python-github-backup I get the following error:
```
Retrieving repositories
Traceback (most recent call last):
  File "/home/cg/.local/bin/github-backup", line 666, in <module>
    main()
  File "/home/cg/.local/bin/github-backup", line 659, in main
    repositories = retrieve_repositories(args)
  File "/home/cg/.local/bin/github-backup", line 389, in retrieve_repositories
    return retrieve_data(args, template, single_request=single_request)
  File "/home/cg/.local/bin/github-backup", line 259, in retrieve_data
    r, errors = _get_response(request, template)
  File "/home/cg/.local/bin/github-backup", line 302, in _get_response
    errors, should_continue = _request_http_error(exc, auth, errors)  # noqa
NameError: global name 'auth' is not defined
```

**Comment by eht16** [comment]
Do you use GIT master? If not, you could try it as this should be fixed by https://github.com/josegonzalez/python-github-backup/commit/2d9825199202e04ff1046d99e33f9876ae0ad916.

I guess you make unauthorized requests to Github and maybe your client IP is rate-limited.
If not, it would probably useful to see your command line.

**Comment by josegonzalez** [comment]
I created a new release just now to fix the issue.

**Comment by geier** [comment]
Thank you for python-github-backup and the fix (it works now)!
